### ISSUE TITLE
Graph only succeeds with less than 20% probability

### ISSUE THREAD

**Issue by dramforever** [jeffswt/pydatagen#1]
Using `master`

```
Python 3.4.3 (default, Jun 29 2015, 12:16:01) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydatagen import *
>>> def test():
...   try:
...     Graph(6, 12, connected=True, weighed=True, weight_range=range(10, 99))
...     return True
...   except:
...     return False
... 
>>> results = [test() for _ in range(20000)]
>>> results.count(True) / len(results)
0.18835
```

**Comment by jeffswt** [comment]
Please post the actual backtrace next time and your random seed!
Thanks~

**Comment by dramforever** [comment]
```
>>> Graph(6, 12, connected=True, weighed=True, weight_range=range(10,99))
Traceback (most recent call last):
  File "C:\Python34\lib\random.py", line 251, in choice
    i = self._randbelow(len(seq))
  File "C:\Python34\lib\random.py", line 228, in _randbelow
    r = getrandbits(k)          # 0 <= r < 2**k
ValueError: number of bits must be greater than zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\Desktop\aaa.py", line 368, in __init__
    self.__try_make_tree()
  File "C:\Users\Administrator\Desktop\aaa.py", line 324, in __try_make_tree
    p = choice(l_n)
  File "C:\Python34\lib\random.py", line 253, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence
```

Try the code a few times and you're sure to get this error

**Comment by jeffswt** [comment]
I will look into this problem when I rewrite this module.
